#server
server.servlet.context-path=/api/v1
server.port=8080

# Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/touragency
spring.datasource.username=quvoncuz
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=quvoncuz@mail.ru
spring.mail.password=
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true

# Liquibase

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/migration/changelog-master.xml
spring.liquibase.default-schema=public

# Click

click.base-url=https://my.click.uz/services/pay
click.service-id=12
click.merchant-id=12
click.secret-key=mc

