### create booking
POST localhost:8080/api/v1/bookings
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "tourId": 1,
  "seatsBooked": 10,
  "note": "To Paris"
}

### booking by user
GET localhost:8080/api/v1/bookings/all
Authorization: Bearer {{jwt}}

### booking by user id ADMIN
GET localhost:8080/api/v1/bookings/by-user/2
Authorization: Bearer {{jwt}}

### booking by agency id
GET localhost:8080/api/v1/bookings/by-agency/   3
Authorization: Bearer {{jwt}}

### cancel booking
DELETE localhost:8080/api/v1/api/v1/bookings/2
Authorization: Bearer {{jwt}}

### update booking
PUT localhost:8080/api/v1/bookings/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "bookingId": 1,
  "seats": 10
}