### create booking
POST localhost:8080/api/v1/booking/create
Content-Type: application/json
X-User-Id: {{userId}}

{
  "tourId": 3,
  "seatsBooked": 10,
  "note": "To Paris"
}

### booking by user
GET localhost:8080/booking/by-user/4
X-User-Id: {{userId}}

### booking by user id ADMIN
GET localhost:8080/booking/by-user/2
X-User-Id: {{userId}}

### booking by agency id
GET localhost:8080/booking/by-agency/2
X-User-Id: {{userId}}

### cancel booking
DELETE localhost:8080/api/v1/booking/2
X-User-Id: {{userId}}

### update booking
PUT localhost:8080/api/v1/booking/1
Content-Type: application/json
X-User-Id: {{userId}}

{
  "bookingId": 1,
  "seats": 10
}