### click post
POST https://18f55f25ec2670.lhr.life/api/v1/click/pay
Content-Type: application/json
X-User-Id: {{userId}}

{
  "tourId": 3,
  "bookingId": 3,
  "returnUrl": "https://18f55f25ec2670.lhr.life/api/v1/tour/all"
}

###