### process payment
POST localhost:8080/api/v1/payments/process
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "bookingId": 1,
  "tourId": 1
}

### find all ADMIN
GET localhost:8080/api/v1/payments/all
Authorization: Bearer {{jwt}}

### find all by user id
GET localhost:8080/api/v1/payments/by-user
Authorization: Bearer {{jwt}}

### find all by tour id
GET localhost:8080/api/v1/payments/by-tour?tourId=2
Authorization: Bearer {{jwt}}