### process payment
POST localhost:8080/payment/process
Content-Type: application/json
X-User-Id: {{userId}}

{
  "bookingId": 1,
  "tourId": 1
}

### find all ADMIN
GET localhost:8080/payment/all
X-User-Id: {{userId}}

### find all by user id
GET localhost:8080/payment/by-user
X-User-Id: {{userId}}

### find all by tour id
GET localhost:8080/payment/by-tour?tourId=2
X-User-Id: {{userId}}