### create rating
POST localhost:8080/api/v1/ratings
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "sourceId": 4,
  "comment": "good",
  "stars": 4,
  "type": "TOUR"
}

### update rating
PUT localhost:8080/api/v1/ratings/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "stars": 5,
  "comment": "perfect"
}

### delete rating
DELETE localhost:8080/api/v1/ratings/1
Authorization: Bearer {{jwt}}

### find by sourceId and type
GET localhost:8080/api/v1/ratings/1?type=TOUR
Authorization: Bearer {{jwt}}

### find by user own
GET localhost:8080/api/v1/ratings/all
Authorization: Bearer {{jwt}}

### find by user own
GET localhost:8080/api/v1/ratings/by-user?userId=2
Authorization: Bearer {{jwt}}