### create tour
POST localhost:8080/api/v1/tours
Content-Type: application/json
X-User-Id: {{userId}}

{
  "title": "Tour to Paris",
  "description": "EURO",
  "destination": "Paris",
  "durationDays": 7,
  "startDate": "2026-05-24",
  "endDate": "2026-05-31",
  "maxSeats": 100,
  "price": 100
}

### update tour
PUT localhost:8080/api/v1/tours/1
Content-Type: application/json
X-User-Id: {{userId}}

{
  "title": "Tour to Paris and Italy",
  "description": "EURO",
  "destination": "Italy",
  "durationDays": 7,
  "startDate": "2026-05-24",
  "endDate": "2026-05-31",
  "maxSeats": 100
}

### update tour price
PUT http://localhost:8080/api/v1/tours/1/price
Content-Type: application/json
X-User-Id: {{userId}}

{
  "price": 150
}

### delete tour
DELETE localhost:8080/api/v1/tours/1
X-User-Id: {{userId}}

### get all tour
GET localhost:8080/api/v1/tours/all

### get all actice tour
GET localhost:8080/api/v1/tours/all-active

### get by id
GET localhost:8080/api/v1/tours/1

### get saved tour
GET localhost:8080/api/v1/tours/saved

### search
GET localhost:8080/api/v1/tours/search?query=Italy