### create tour
POST localhost:8080/api/v1/tour/create
Content-Type: application/json
X-User-Id: {{userId}}

{
  "title": "Tour to Paris",
  "description": "EURO",
  "destination": "Paris",
  "durationDays": 7,
  "startDate": "2026-05-24",
  "endDate": "2026-05-31",
  "maxSeats": 100,
  "price": 100
}

### update tour
PUT localhost:8080/api/v1/tour/1
Content-Type: application/json
X-User-Id: {{userId}}

{
  "title": "Tour to Paris and Italy",
  "description": "EURO",
  "destination": "Italy",
  "durationDays": 7,
  "startDate": "2026-05-24",
  "endDate": "2026-05-31",
  "maxSeats": 100,
  "price": 100
}

### delete tour
DELETE localhost:8080/api/v1/tour/1
X-User-Id: {{userId}}

### get all tour
GET localhost:8080/api/v1/tour/all

### get all actice tour
GET localhost:8080/api/v1/tour/all-active

### get by id
GET localhost:8080/api/v1/tour/2

### get saved tour
GET localhost:8080/api/v1/tour/saved

### search
GET localhost:8080/api/v1/tour/search?query=Italy