-- liquibase formatted sql

-- changeset dev:v1_005_payments
create table payments
(
    amount     bigint,
    booking_id bigint
        constraint foreign_key_booking_for_payment
            references bookings,
    created_at timestamp,
    id         bigint generated by default as identity
        primary key,
    tour_id    bigint
        constraint foreign_key_tour_for_payment
            references tours,
    user_id    bigint
        constraint foreign_key_profile_for_payment
            references profiles,
    status     varchar(255),
    cancelled_at timestamp
    );