-- liquibase formatted sql

-- changeset dev:v1_007_ratings
create table ratings
(
    stars      integer,
    created_at timestamp,
    id         bigint generated by default as identity
        primary key,
    source_id  bigint,
    user_id    bigint
        constraint foreign_key_profile_rating
            references profiles,
    comment    varchar(255),
    type       varchar(255)
        constraint rating_type_check
            check ((type)::text = ANY ((ARRAY ['AGENCY'::character varying, 'TOUR'::character varying])::text[]))
    );