-- liquibase formatted sql

-- changeset dev:v1_001_profiles
create table profiles
(
    is_active         boolean,
    is_created_agency boolean,
    created_at        timestamp,
    id                bigint generated by default as identity
        primary key,
    email             varchar(255),
    full_name         varchar(255),
    gender            varchar(255)
        constraint profile_gender_check
            check ((gender)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    password          varchar(255),
    role              varchar(255)
        constraint profile_role_check
            check ((role)::text = ANY
                   ((ARRAY ['AGENCY'::character varying, 'ADMIN'::character varying, 'USER'::character varying])::text[])),
    username          varchar(255)
);