-- liquibase formatted sql

-- changeset dev:v1_005_payments
create table payment
(
    amount     bigint,
    booking_id bigint
        constraint foreign_key_booking_for_payment
            references booking,
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    tour_id    bigint
        constraint foreign_key_tour_for_payment
            references tour,
    user_id    bigint
        constraint foreign_key_profile_for_payment
            references profile,
    status     varchar(255),
    cancelled_at timestamp(5)
    );