-- liquibase formatted sql

-- changeset dev:v1_008_saved_tours
create table saved_tours
(
    created_at timestamp,
    id         bigint generated by default as identity
        primary key,
    tour_id    bigint
        constraint foreign_key_tour_for_saved_tour
            references tours,
    user_id    bigint
        constraint foreign_key_profile_for_saved_tour
            references profiles
);