-- liquibase formatted sql

-- changeset dev:v1_008_saved_tours
create table saved_tour
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    tour_id    bigint
        constraint foreign_key_tour_for_saved_tour
            references tour,
    user_id    bigint
        constraint foreign_key_profile_for_saved_tour
            references profile
);