-- liquibase formatted sql

-- changeset dev:v1_004_bookings
create table booking
(
    seats_booked integer,
    booked_at    timestamp(6),
    id           bigint generated by default as identity
        primary key,
    paid_amount  bigint,
    total_price  bigint,
    tour_id      bigint
        constraint foreign_key_tour_for_booking
            references tour,
    user_id      bigint
        constraint foreign_key_profile_for_booking
            references profile,
    note         varchar(255),
    status       varchar(255)
        constraint booking_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELED'::character varying])::text[])),
    cancelled_at timestamp(6),
    cancel_reason varchar(200)
    );