-- liquibase formatted sql

-- changeset dev:v1_003_tours
create table tour
(
    available_seats integer,
    duration_days   integer,
    end_date        date,
    is_active       boolean,
    max_seats       integer,
    rating          double precision,
    start_date      date,
    agency_id       bigint
        constraint foreign_key_agency_for_tour
            references agency,
    created_at      timestamp(6),
    id              bigint generated by default as identity
        primary key,
    price           bigint,
    view_count      bigint,
    description     varchar(255),
    destination     varchar(255),
    status          varchar(255)
        constraint tour_status_check
            check ((status)::text = ANY
        ((ARRAY ['ACTIVE'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'SOLD_OUT'::character varying])::text[])),
    title           varchar(255)
);